# Generated by Django 4.1 on 2024-02-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Image",
            field=models.ImageField(blank=True, default="", upload_to="products"),
        ),
    ]
